"""Initial migration

Revision ID: d31aa0641081
Revises: d1b3db3d81c0
Create Date: 2024-06-09 13:22:51.893026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31aa0641081'
down_revision = 'd1b3db3d81c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_index('ix_employee_name')
        batch_op.create_index(batch_op.f('ix_employee_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_phone'))
        batch_op.drop_index(batch_op.f('ix_employee_first_name'))
        batch_op.drop_index(batch_op.f('ix_employee_created_at'))
        batch_op.drop_index(batch_op.f('ix_employee_city'))
        batch_op.drop_index(batch_op.f('ix_employee_address'))
        batch_op.drop_index(batch_op.f('ix_employee_name'))
        batch_op.create_index('ix_employee_name', ['name'], unique=1)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
